name: CI

on:
  push:
  pull_request:
  release:
    types: [released]

env:
  PYTHONUTF8: 1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          architecture: "x64"
      - name: Build
        run: |
          cd src
          cp ../README.md ./README.md
          python -m pip install --upgrade build twine
          python -m build -o ../dist
      - name: Upload package artifacts
        uses: actions/upload-artifact@v3
        with:
          name: package
          path: ./dist
  test:
    needs: build
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        python: ["3.10"]
        experimental: [false]
        include:
          - os: ubuntu-latest
            python: "3.11.0-rc.2"
            experimental: true
    continue-on-error: ${{ matrix.experimental }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          persist-credentials: false
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
          architecture: "x64"
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: package
          path: ./dist
      - name: Install
        run: python -m pip install ./dist/sfpy-0.0.1-py3-none-any.whl
      - name: Help
        run: python -m sfpy --help

        